// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://depvzofgnfswmhtdvdoh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRlcHZ6b2ZnbmZzd21odGR2ZG9oIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI1ODEzNDIsImV4cCI6MjA1ODE1NzM0Mn0.XUqypXnP8Zs3-QHkIxmHkZUruWNzoX05bqlTwYe3ez0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);